name: Auto update go dependencies

on:
  schedule:
    # runs daily at 12:00 am
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - 'release/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update-go-dependencies:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v4
      with:
        persist-credentials: false
          
    - name: Go setup
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true
        cache: true
    - name: Install dependencies
      run: go get -t -u ./...
    - name: Run go mod tidy
      run: go mod tidy
    - name: Build the project
      run: go build ./...
    - name: Generate change summary
      id: changes
      run: |
        echo "## Changes Summary" > changes.md
        echo "" >> changes.md
        if git diff --name-only | grep -q .; then
          echo "### Modified files:" >> changes.md
          git diff --name-only | sed 's/^/- /' >> changes.md
          echo "" >> changes.md
          echo "### Dependency changes:" >> changes.md
          if git diff go.mod | grep -E '^[+-]' | grep -v '^[+-]{3}' | grep -v '^[+-]module' | grep -v '^[+-]go ' > /dev/null; then
            git diff go.mod | grep -E '^[+-]' | grep -v '^[+-]{3}' | grep -v '^[+-]module' | grep -v '^[+-]go ' >> changes.md
          else
            echo "- No dependency changes detected" >> changes.md
          fi
        else
          echo "- No changes detected" >> changes.md
        fi
        echo 'CHANGES<<EOF' >> $GITHUB_OUTPUT
        cat changes.md >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7.0.8
      with:
        commit-message: Update report
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        title: 'chore: Update Dependencies'
        body: |
          Updated to latest go dependencies.
          
          ${{ steps.changes.outputs.CHANGES }}
        assignees: danielewood
        reviewers: danielewood
        draft: false
        branch: dependency-bump
        delete-branch: true

    - name: Check output
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"