name: Auto update go dependencies

on:
  schedule:
    # runs daily at 12:00 am
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - 'release/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update-go-dependencies:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v4
      with:
        persist-credentials: false
          
    - name: Go setup
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true
        cache: true
             
    - name: Run auto dependency update 
      uses: chouquette/dependencies-autoupdate@2f7e5d4d13fb748047c80848e7b73314005450a9
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: "'go get -u && go mod tidy'"
        # update-path: "'./test/go'"
        on-changes-command: "'go build ./...'"
      continue-on-error: false
